### ISSUE TITLE
Cannot upload .7z file

### ISSUE THREAD

**Issue by jeffythedragonslayer** [uttori/uttori-wiki#34]
This page incorrectly uses the .smc file extension (which stands for Super Magicom, a copier) for a ROM without a copier header:

https://wiki.superfamicom.org/how-to-write-to-dsp-registers-without-any-spc-700-code

When I tried to change it to .sfc and re-upload the manual_dsp.7z file, I got this error:

![image](https://github.com/uttori/uttori-wiki/assets/13253146/21cf6a1b-a82c-4a30-b61c-901a79ca1459)

**Comment by MatthewCallis** [comment]
Which browser was this in? Could you verify the files MIME type here https://www.htmlstrip.com/mime-file-type-checker ? I just downloaded and reuploaded the `manual_dsp.7z` and didn't see this message, making me think the files MIME type is wrong or being seen as something unexpected.

**Comment by MatthewCallis** [comment]
Should be fixed now!
